### ISSUE TITLE
Create Jupyter Notebook on how to develop a transformer

### ISSUE THREAD

**Issue by Chris-Schnaufer** [AgPipeline/issues-and-projects#13]
- [x] Review how other groups have done this (see slack message)
- [x] Show how to develop a transformer using Jupyter notebook so that it's copy and paste to actual transformer. 
- [x] Create a docker instance for CyVerse DE app with resulting notebook

**Comment by julianpistorius** [comment]
- [ ] Talk to Adam Thornton from LSST
- [ ] Attend Python Meetup in December where Adam will present on his work for this
  - It will be based on this presentation: https://athornton.github.io/JupyterCon-2018-talk/#/step-1
- [ ] Investigate SoS Polyglot Notebooks and SoS Workflow System 
  - https://vatlab.github.io/sos-docs/
  - I played with this some time ago - it seemed promising

**Comment by julianpistorius** [comment]
Related: Proposal to evolve transformer architecture #27

**Comment by Sithyphus** [comment]
This is located in a separate repository, I will link it here
https://github.com/Sithyphus/jupyter-transformer-sandbox/tree/develop
All that's left should be to update the readme (it's a bit bare) and some documentation here and there.
Also talk to the DE team and see what sort of "compatibility" issues that may or may not be a problem, I'll make a separate ticket and link it to this.
Also probably a good idea to have someone review it, most likely Chris and I will get together to do that. I could make a pull request of sorts but most likely I'll just have a quick talk to him whenever we're not too busy.

**Comment by Chris-Schnaufer** [comment]
@Sithyphus  Is this done with all the follow on work?

**Comment by dlebauer** [comment]
Would be great to have this as a demo at our next sprint review
