### ISSUE TITLE
Take over responsibility for cache server

### ISSUE THREAD

**Issue by dlebauer** [AgPipeline/issues-and-projects#21]
Need to coordinate with Sean Stevens at UA

* Review [TERRAREF cache server handoff docs](https://docs.google.com/document/d/1gIT7vioMxJsXUESMJQORB0lTPX9PaMHwIN0i_XtkN0U/edit)
* Document these protocols
* Add scripts to github repository with restricted access
* Automate cache clearing

[11/27/2019 - Chris S: I added 'with restricted access' to github repository line]

**Comment by julianpistorius** [comment]
Progress: Found a workaround for the IP address whitelist issue. We have access to a small IP address range which JD will add to the whitelist. We can then use persistent or ephemeral 'secure jump hosts' or 'bastion hosts' and assign them IP addresses in that range.

Waiting to hear back from JD about when that happens.

**Comment by julianpistorius** [comment]
Progress: Sean S says that the request to open the firewall rules have to come via Matt Rahr. He's offered to get in touch with Matt to kick off the process. He'll CC me.

**Comment by julianpistorius** [comment]
Progress: Andy Monteverde is in the process of opening the firewall for the IP address range I gave Sean.

**Comment by julianpistorius** [comment]
Progress: I have confirmed I have access to the gantry cache server from an IP address in the requested range.

:tada:

**Comment by julianpistorius** [comment]
@dlebauer I think this should be an epic.

**Comment by Chris-Schnaufer** [comment]
Changing into an Epic  @julianpistorius break out into separate tickets
