### ISSUE TITLE
Determine minimum required transfer rate from Cache Server

### ISSUE THREAD

**Issue by dlebauer** [AgPipeline/issues-and-projects#22]
Based on data transfer rates to date, it is clear that we don't need the 1 Gigabit line that we currently have and costs thousands / month. What is the minimum transfer rate from MAC to the internet that we need so that we can keep up with historical data generation rates?

Discuss w/ JD and Sean Stevens, then let Matt Rahr know requirements

**Comment by julianpistorius** [comment]
@dlebauer Do you happen to have the historical data generation rates somewhere? If I don't hear from you before Monday I'll do a quick search through the Google Drive ('quick' Hah. 😅).

**Comment by julianpistorius** [comment]
Update: Sent email to J.D. & Sean.

**Comment by dlebauer** [comment]
@max-zilla do you know what happened to http://terra-logging.ncsa.illinois.edu/?

**Comment by dlebauer** [comment]
We resolved this via email and ended up reducing the data transfer rates by 1/2
