### ISSUE TITLE
Come up with plan to move TERRA REF data archives from NCSA to UA GDrive

### ISSUE THREAD

**Issue by dlebauer** [AgPipeline/issues-and-projects#23]
Need to archive data from the Storage Condo and Nearline tape at UIUC on GDrive using Globus transfer.

Coordinate with Sean Stevens to set up a plan. Allocation on Storage Condo officially ends in December (?) and tape in March of next year, so we need to transfer ~1PB of the zipped archived files by then.

**Comment by Chris-Schnaufer** [comment]
This is to figure out how to move the data - tactical planning

**Comment by dlebauer** [comment]
I also submitted an allocation request to TACC ...

**Comment by julianpistorius** [comment]
I have reached out to Sean Stevens to find out current status of this, and to see if I can help.

**Comment by srstevens** [comment]
I will post a file listing that wil linclude what's transferred so far and what hasn't.  I'll try to get that together this afternoon. 

The data is moving into Google Drive... what I've seen is the endpoint kicks back too busy.  I haven't timed it exactly, but I know with other Google Drive endpoints there is a 1TB/day ingest limit imposed by Google.  This may be what we're running into.

**Comment by Chris-Schnaufer** [comment]
@julianpistorius please get an update from Sean on this

**Comment by julianpistorius** [comment]
Hi @srstevens! Any updates on this?

If 1TB/day is a hard limit then it'll take almost three years (!!) and we'll have to come up with another solution.

**Comment by julianpistorius** [comment]
> I also submitted an allocation request to TACC ...

Any update on this @dlebauer ?

**Comment by dlebauer** [comment]
Unless perhaps we can set up multiple endpoints? And if we focus on archiving the raw_data first, that will reduce the volume by perhaps ~2-3x

**Comment by srstevens** [comment]
Here's a csv (renamed .txt to make github happy) file tracking archive transfers from ncsa#Nearline to UA GDrive TERRA-REF.  
[terraref_archive.transfers.txt](https://github.com/AgPipeline/issues-and-projects/files/3959171/terraref_archive.transfers.txt)

We might be able to transfer more with multiple users running transfers.  

The usual time out with the endpoint comes up as a rate limit, which could be at the endpoint not user level.  At least on GDrive endpoints I've dealt with, this has to do with Google Drive API calls made by the application.  Part of the process of setting up the endpoint, Globus suggests increasing these quotas and also requesting Google increase some that the admin cannot adjust.

**Comment by srstevens** [comment]
All transfers out of Nearline are complete.  I have a few files that got copied to the wrong directory that need to be removed, but as far as I can tell I don't have permission to remove them.  The files are:

UA GDrive TERRA-REF:/ua-mac/archive/raw_data_S2/
arch_ua-mac_raw_data_SWIR_S1.p1.tar
arch_ua-mac_raw_data_VNIR_S1.p10.tar
arch_ua-mac_raw_data_VNIR_S1.p11.tar
arch_ua-mac_raw_data_stereoTop_S1.p2.tar
arch_ua-mac_raw_data_stereoTop_S1.p7.tar

I was also going to move all the md5 files from the top level into the /ua-mac/archive/md5sums directory, but I also don't appear to have premissions to move those.  I can try downloading and uploading if needed, but if someone else has better access it might be easier for them to just move the files.

**Comment by julianpistorius** [comment]
Blake wants to meet about this.

**Comment by julianpistorius** [comment]
Going to close this and merge with the [NCSA -> TACC issue](https://github.com/AgPipeline/data/issues/13)
