### ISSUE TITLE
Upgrade jupyter notebook to jupyter lab

### ISSUE THREAD

**Issue by Sithyphus** [AgPipeline/issues-and-projects#28]
Jupyter Lab seems to be the future of jupyter and code notebooks so it may come up that everything we do currently in regular jupyter notebook should work with jupyter lab.

This shouldn't really be a problem since both use the same file, labs simply have more user facing functionality but it's good to keep this in mind.

**Comment by Chris-Schnaufer** [comment]
@dlebauer This can most likely be closed? Is that the intent of putting it into Review/QA?
