### ISSUE TITLE
Process captured RGB data as it arrives through to canopy cover & save data products

### ISSUE THREAD

**Issue by Chris-Schnaufer** [AgPipeline/issues-and-projects#39]
**Task to do**
Pre-production testing of process through final analysis step and store resulting data products

**Reason**
Ensure environment is setup to correctly process data and all data products are available. Allows follow on testing of plot-level analysis with Urbana generated data

**Result**
Able to access final analysis results to compare against current system. Able to compare intermediate data products against Urbana generated data.

**Comment by julianpistorius** [comment]
Related: #29

**Comment by Chris-Schnaufer** [comment]
The goal of this is to run sets of data through the workflow and ensure resulting data is staged and available for testing

**Comment by julianpistorius** [comment]
My interpretation:

- [ ] Generate a Makeflow workflow for a single 'capture'* of the field


Footnotes:

\* 'capture' - When you decide it starts and ends

**Comment by julianpistorius** [comment]
> Ask John X. & Sateesh how they're going to generate their parallel processing Makeflow

They're running a sub-workflow for each item in a list of IRODS directory paths:

https://github.com/uacic/starTerra/tree/master/stereoTop
