### ISSUE TITLE
Provide technical documentation for base template-lidar-plot

### ISSUE THREAD

**Issue by Chris-Schnaufer** [AgPipeline/issues-and-projects#43]
**Task to do**
Create technical documentation for template-lidar-plot and add it to the Organization web site

**Reason**
Documenting technical approach to repo, and what's provided by code is helpful for developers

**Result**
Technical documentation on the Lidar plot-level template is available

Note:
1. starting with the existing template-rgb-plot technical documentation would most likely shorten the timneframe needed to produce the documentation

**Comment by Sithyphus** [comment]
PR for this is located here
https://github.com/AgPipeline/AgPipeline.github.io/pull/3
