### ISSUE TITLE
Migrate canopy-height transformer to use new template-lidar-plot template as starting point

### ISSUE THREAD

**Issue by Chris-Schnaufer** [AgPipeline/issues-and-projects#45]
**Task to do**
Use template-lidar-plot template repo as the basis for the canopy height transformer

**Reason**
Much less code to maintain and standardization of plot-level transformers

**Result**
Updated canopy-height transformer

**Comment by dlebauer** [comment]
@Chris-Schnaufer does this mean to move the code from this repo https://github.com/AgPipeline/transformer-las2height?

**Comment by Sithyphus** [comment]
https://github.com/AgPipeline/template-canopy-height

**Comment by Sithyphus** [comment]
Ignore the above it's here.
https://github.com/ua-diag-pipeline/template-canopy-height
