### ISSUE TITLE
A small RGB dataset to test pipeline

### ISSUE THREAD

**Issue by julianpistorius** [AgPipeline/issues-and-projects#49]
**Task to do**
See https://github.com/AgPipeline/computing-pipeline/pull/46#discussion_r353252092

> Would it be possible to provide a small dataset that could be used to run this? It could be available on Google Drive under the account that Jorge setup in .tar format?

**Reason**

To allow easy testing of the pipeline.

**Result**

One or more sample data sets (different sizes) available from a URL (e.g. Google Drive or CyVerse DE public link)

**Comment by Chris-Schnaufer** [comment]
https://drive.google.com/file/d/1el3BW6-zoJiJ_tv39JBENBYc7bakMXxT/view?usp=sharing

**Comment by dlebauer** [comment]
done - julian has a test dataset
