### ISSUE TITLE
Put the version number of the docker images to use in the jx-args.json file

### ISSUE THREAD

**Issue by julianpistorius** [AgPipeline/issues-and-projects#52]
> What do you think of putting the version number of the docker images to use in the jx-args.json file?

_Originally posted by @Chris-Schnaufer in https://github.com/AgPipeline/computing-pipeline/pull/46_

**Comment by Chris-Schnaufer** [comment]
Waiting on PR https://github.com/AgPipeline/drone-makeflow/pull/18
