### ISSUE TITLE
Delete *.png.aux.xml files during Makeflow cleanup

### ISSUE THREAD

**Issue by julianpistorius** [AgPipeline/issues-and-projects#53]
> *.png.aux.xml is not a needed result - it's a result of the transformation app.

_Originally posted by @Chris-Schnaufer in https://github.com/AgPipeline/computing-pipeline/pull/46_

**Comment by Chris-Schnaufer** [comment]
@julianpistorius Is this still relevant

**Comment by Chris-Schnaufer** [comment]
@julianpistorius Is this ticket still relevant?

**Comment by julianpistorius** [comment]
I don't think so.
