### ISSUE TITLE
Create transformers for hyper-spectral data

### ISSUE THREAD

**Issue by Chris-Schnaufer** [AgPipeline/issues-and-projects#57]
**Task to do**
Migrate TERRA REF extractors to AgPipeline transformers to process hyper-spectral data, add plot clipping https://github.com/terraref/computing-pipeline/issues/606

**Reason**
Adding another sensor processing pipeline

**Result**
Able to process hyper-spectral data

**Comment by Chris-Schnaufer** [comment]
https://github.com/AgPipeline/AgPipeline.github.io/pull/2

**Comment by dlebauer** [comment]
next steps:
* clipping to plot
* computing indices
* putting indices in BETYdb
* and only then ... port to extractors

**Comment by Chris-Schnaufer** [comment]
Repo: https://github.com/AgPipeline/transformer-hyperspectral - includes instructions on running a testing instance with data

Wrote tickets on additional work items per David's comments above
