### ISSUE TITLE
Better merge original README.md into new README for transformer-ply2las

### ISSUE THREAD

**Issue by Chris-Schnaufer** [AgPipeline/issues-and-projects#66]
**Task to do**
The original README.md contents are appended to the new README.md. This task it to integrate the original README.md contents in with the new content.

**Reason**
There's no reason to keep the original content separate from the new content.

**Result**
A README that only contains relevant information for the transformer

**Comment by Sithyphus** [comment]
PR is right here
https://github.com/AgPipeline/transformer-ply2las/pull/5
