### ISSUE TITLE
Create mean temperature Transformer

### ISSUE THREAD

**Issue by Chris-Schnaufer** [AgPipeline/issues-and-projects#69]
**Task to do**
Create a mean temperature transformer

**Reason**
Allows a complete FLIR pipeline

**Result**
Able to process data to produce mean temperature

**Notes**
Works on a single plot image

**Comment by KristinaRiemer** [comment]
What is the status on this @Chris-Schnaufer? Is there a PR associated with this?

**Comment by Chris-Schnaufer** [comment]
@KristinaRiemer This is done
