### ISSUE TITLE
Post notes from meet with pipeline developers to discuss dashboard

### ISSUE THREAD

**Issue by MagicMilly** [AgPipeline/issues-and-projects#70]
**Task to do**
Meet with Jorge, Chris, Julian, and other developers involved in pipeline. 

**Reason**
Gain an understanding of what developers / end-users would want and need from a dashboard.

**Result**
Open communication with developers about what they need in a dashboard to get started on researching the best tools for this project.

**Comment by KristinaRiemer** [comment]
Potentially write user stories for this @MagicMilly

**Comment by Chris-Schnaufer** [comment]
@MagicMilly What's the status on this?

**Comment by MagicMilly** [comment]
[Pull Request](https://github.com/az-digitalag/organization/pull/170) can be merged after @julianpistorius reviews notes to see if anything was missed / needs to be added
