### ISSUE TITLE
Create envlog2netcdf Transformer

### ISSUE THREAD

**Issue by Chris-Schnaufer** [AgPipeline/issues-and-projects#75]
**Task to do**
Write a transformer for the AgPipeline at UA based upon [extractor](https://github.com/terraref/extractors-environmental/tree/master/envlog2netcdf)

**Reason**
Completing pipeline

**Result**
Have a working transformer

**Comment by KristinaRiemer** [comment]
What is the status on this @Chris-Schnaufer?

**Comment by Chris-Schnaufer** [comment]
@KristinaRiemer This is done, just needed to be moved
